


server.port=8080
spring.application.name=security-gateway
spring.main.allow-circular-references=true

spring.datasource.url=jdbc:postgresql://localhost:5432/CMMS
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

app.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
app.jwt.expiration-ms=86400000
app.jwt.cookie-name=jwt-token




# If using older Spring Cloud with Hystrix
hystrix.command.default.execution.isolation.strategy=SEMAPHORE

# If using Spring Security context propagation
spring.security.strategy=MODE_INHERITABLETHREADLOCAL





# Force this service to cooperate with the others
spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=20000